version: "3.6"
services:
  # DB
  db:
    environment:
      - POSTGRES_HOST
      - POSTGRES_PORT
    build:
      context: ./back/db
    ports:
      - ${POSTGRES_PORT}:5432
  # Backend application
  backend:
    environment:
      - POSTGRES_HOST
      - POSTGRES_PORT
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DB

      - BACKEND_PORT
      - CLIENT_ORIGIN

      - EMAIL_FROM
      - SMTP_HOST
      - SMTP_USER
      - SMTP_PASS
      - SMTP_PORT

      - TOKEN_EXPIRED_IN
      - TOKEN_MAXAGE

      - TOKEN_SECRET

      - GOOGLE_OAUTH_CLIENT_ID
      - GOOGLE_OAUTH_CLIENT_SECRET
      - GOOGLE_OAUTH_REDIRECT_URL

      - GITHUB_OAUTH_CLIENT_ID
      - GITHUB_OAUTH_CLIENT_SECRET
      - GITHUB_OAUTH_REDIRECT_URL
    build:
      context: ./back/service
    volumes:
      - log-proxy:/log
    depends_on:
      - proxy
    ports:
      - ${BACKEND_PORT}:${BACKEND_PORT}

  # Frontend web application
  frontend:
    environment:
      - FRONTEND_PORT

      - REACT_APP_BACKEND_ADDRESS
      - REACT_APP_BACKEND_PORT

      - REACT_APP_GOOGLE_OAUTH_CLIENT_ID
      - REACT_APP_GOOGLE_OAUTH_REDIRECT

      - REACT_APP_GITHUB_OAUTH_CLIENT_ID
      - REACT_APP_GITHUB_OAUTH_REDIRECT
    build:
      context: ./front/library
    depends_on:
      - backend
    ports:
      - ${FRONTEND_PORT}:3000
  # External proxy
  proxy:
    environment:
      - SERVER_IP
      - SERVER_NAME
      - SERVER_PORT
      - FRONTEND_PORT
      - BACKEND_PORT
    build: ./proxy
    volumes:
      - log-proxy:/var/log/nginx
    ports:
      - ${SERVER_PORT}:${SERVER_PORT}
    depends_on:
      - db
    command: /bin/bash /bin/start_nginx.sh
  fail2ban:
    image: lscr.io/linuxserver/fail2ban:latest
    container_name: fail2ban
    cap_add:
      - NET_ADMIN
      - NET_RAW
    network_mode: host
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - VERBOSITY=-vv #optional
    volumes:
      - ./proxy:/config
      - /var/log:/var/log:ro
      - log-proxy:/remotelogs/nginx:ro
    restart: unless-stopped
    depends_on:
      - frontend
volumes:
  log-backend:
  log-proxy:
  log-file2ban: