version: "3.6"
services:
  # DB
  db:
    environment:
      - POSTGRES_HOST
      - POSTGRES_PORT
    build:
      context: ./back/db
    ports:
      - ${POSTGRES_PORT}:5432
  # Backend application
  backend:
    environment:
      - POSTGRES_HOST
      - POSTGRES_PORT
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DB

      - BACKEND_PORT
      - EXTERNAL_BACKEND_ADDRESS
      - EXTERNAL_BACKEND_PORT

      - EMAIL_FROM
      - SMTP_HOST
      - SMTP_USER
      - SMTP_PASS
      - SMTP_PORT

    build:
      context: ./back/service
    depends_on:
      - db
    ports:
      - ${BACKEND_PORT}:${BACKEND_PORT}

  # Frontend web application
  frontend:
    build:
      context: ./front/library
    depends_on:
      - backend
    ports:
      - ${FRONTEND_PORT}:3000
  # External proxy
  proxy:
    network_mode: bridge
    environment:
      - PROXY_REDIRECT_ADDRESS
      - SERVER_NAME
      - SERVER_PORT
      - FRONTEND_PORT
      - BACKEND_PORT
    build: ./proxy
    volumes:
      - ./proxy/log/nginx:/var/log/nginx
    ports:
      - ${SERVER_PORT}:${SERVER_PORT}
    command: /bin/bash /bin/start_nginx.sh
  fail2ban:
    image: lscr.io/linuxserver/fail2ban:latest
    container_name: fail2ban
    cap_add:
      - NET_ADMIN
      - NET_RAW
    network_mode: host
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - VERBOSITY=-vv #optional
    volumes:
      - ./proxy:/config
      - ./proxy/log/nginx:/remotelogs/nginx:ro
    restart: unless-stopped
    depends_on:
      - proxy
  logrotate:
    image: thommeo/logrotate
    volumes:
      - ./proxy/log/nginx:/var/log/rotate
    restart: always
    depends_on:
      - fail2ban
