export const LOGIN_STATUS_SIGNED_UP = 'SIGNED_UP';
export const LOGIN_STATUS_VERIFIED = 'VERIFIED';
export const LOGIN_STATUS_LOGGED_IN = 'LOGGED_IN';
export const LOGIN_STATUS_PASSWORD_RESET = 'PASSWORD_RESET';
export const LOGIN_STATUS_PASSWORD_FORGOT = 'PASSWORD_FORGOT';
